AllCops:
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "config.ru"
    - "Gemfile"
    - "Rakefile"
    - "config/**/*"
  TargetRubyVersion: 2.4

  DisplayCopNames: true
  ExtraDetails: true

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - "config/**/*"
