language: ruby
cache: bundler
rvm:
  - 2.3.0
bundler_args: --without production
before_script:
  - RAILS_ENV=test bundle exec rake db:setup
script:
  - bundle exec rake test
  - 'if [ "$TRAVIS_PULL_REQUEST" == false ]; then echo "TRAVIS_PULL_REQUEST is unset, skipping Pronto"; else PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} bundle exec pronto run -f github_pr; fi'
